# Hotswap:                                                #
# ------------------------------------------------------- #
# If chestplate is disabled, elytra will also be disabled #
swap:
  helmet: true
  chestplate: true
  leggings: true
  boots: true
  elytra: true

# Container Prevention                                #
# --------------------------------------------------- #
# If enabled, Hotswap will override chests/containers #
container-swap: false

# Multiple World Support                                           #
# ---------------------------------------------------------------- #
# If all is set to false, Hotswap will only work in default worlds #
worlds:
  all: true



# DO NOT CHANGE #
# ------------- #
first: true